alias l='ls -lah'
alias ..='cd ..'
alias cdw='cd /var/www/project'

alias a2rs='sudo /etc/init.d/apache2 restart'
alias a2err='sudo tail -f /var/log/apache2/error.log'
alias a2acc='sudo tail -f /var/log/apache2/access.log'
alias ngacc='sudo tail -f /var/log/nginx/access.log'
alias ngerr='sudo tail -f /var/log/nginx/error.log'
alias ngrs='sudo service nginx restart'
alias ngt='sudo service nginx configtest'

alias sf='php app/console'
alias sfcc='php app/console cache:clear'
alias sfdb='composer database-reset'
alias sfdevl='tail -f /var/www/api/app/logs/dev.log'
alias sfprodl='tail -f /var/www/api/app/logs/prod.log'
alias sfrmc='rm -rf app/cache/* app/logs/*'
alias sft='composer test'
