{
  imports = [
    ./age.nix
    ./bluetooth.nix
    ./dankgreeter.nix
    ./eternal-terminal.nix
    ./gnome.nix
    ./gnome-keyring.nix
    ./i18n.nix
    ./mosh.nix
    ./networking.nix
    ./printing.nix
    ./sops.nix
    ./sound.nix
    ./ssh.nix
    ./tuigreet.nix
    ./users.nix
  ];
}
