name: keyboards

on:
  push: ~
    # branches:
    #   # - main
    #   - v2
    # paths:
    #   - keyboards
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: cantor
          keymap: deuzu
          local-keymap-path: keyboards/cantor/keymaps/deuzu
          output-dir: keyboards/build
      - uses: actions/upload-artifact@v4
        with:
          name: qmk-firmware-cantor-deuzu
          path: keyboards/build
